version: 2
updates:
  - package-ecosystem: "gomod"
    directory: ""
    schedule:
      interval: "daily"
    commit-message:
      prefix: "gomod"
    open-pull-requests-limit: 10
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: ""
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions"
    open-pull-requests-limit: 10
    target-branch: "main"
