apiVersion: apps/v1
kind: Deployment
metadata:
  name: enphase-envoy-prometheus-exporter
  labels:
    helm.sh/chart: enphase-envoy-prometheus-exporter
    app.kubernetes.io/name: enphase-envoy-prometheus-exporter
    app.kubernetes.io/instance: enphase-envoy-prometheus-exporter
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: enphase-envoy-prometheus-exporter
      app.kubernetes.io/instance: enphase-envoy-prometheus-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enphase-envoy-prometheus-exporter
        app.kubernetes.io/instance: enphase-envoy-prometheus-exporter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: enphase-envoy-prometheus-exporter
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: enphase-envoy-prometheus-exporter
          env:
            - name: EEPE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: username
                  optional: false
            - name: EEPE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: password
                  optional: false
            - name: EEPE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: host
                  optional: false
            - name: EEPE_SERIALNUMBER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: serialNumber
                  optional: false
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
