apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: enphase-envoy-prometheus-exporter
  labels:
    app.kubernetes.io/name: enphase-envoy-prometheus-exporter
    app.kubernetes.io/instance: enphase-envoy-prometheus-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
    app.kubernetes.io/name: enphase-envoy-prometheus-exporter
    app.kubernetes.io/instance: enphase-envoy-prometheus-exporter
  endpoints:
    - port: http
