replicaCount: 1
revisionHistoryLimit: 0

image:
  repository: ghcr.io/florisfeddema/enphase-envoy-prometheus-exporter
  pullPolicy: IfNotPresent
  tag: ""

existingSecret: ''

imagePullSecrets: [ ]

resources:
  limits:
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 16Mi
